export const bankOptions = [
  { value: "BAC A BANK", label: "BAC A BANK" },
  { value: "Nam A Bank", label: "Nam A Bank" },
  { value: "Vietcombank", label: "Vietcombank" },
  { value: "Techcombank", label: "Techcombank" },
  { value: "ACB", label: "ACB" },
  {
    value: "BIDV",
    label: "BIDV",
  },
  { value: "VietinBank", label: "VietinBank" },
  { value: "MBBank", label: "MBBank" },
  { value: "VPBank", label: "VPBank" },
  { value: "TPBank", label: "TPBank" },
  { value: "SHB - Sài Gòn - Hà Nội", label: "SHB - Sài Gòn - Hà Nội" },
  { value: "HDBank", label: "HDBank" },
  { value: "OCB - Phương Đông", label: "OCB - Phương Đông" },
  { value: "SCB - Sài Gòn", label: "SCB - Sài Gòn" },
  { value: "Eximbank", label: "Eximbank" },
  { value: "Sacombank", label: "Sacombank" },
  { value: "LienVietPostBank", label: "LienVietPostBank" },
  { value: "MSB - Maritime Bank", label: "MSB - Maritime Bank" },
  { value: "ABBANK", label: "ABBANK" },
  { value: "VIB - Quốc tế", label: "VIB - Quốc tế" },
  { value: "SeABank", label: "SeABank" },
];
